preamble:
- label: Motivation
  desc: Effective interface design requires basic knowledge of security psychology. Many attacks do not have a technological basis, but exploit human propensities and vulnerabilities. “Only amateurs attack machines; professionals target people” (Bruce Schneier, see [Phishing Has Gotten Very Good](https://www.schneier.com/blog/archives/2013/03/phishing_has_go.html))

topics:
- label: t01
  desc: Applied psychology and security policies
- label: t02
  desc: Security economics
- label: t03
  desc: Regulatory environments – responsibility, liability and self-determination
- label: t04
  desc: Organizational vulnerabilities and threats
- label: t05
  desc: Usability design and security
- label: t06
  desc: Pretext, impersonation and fraud, e.g., phishing and spear phishing (cross-reference IAS/Threats and Attacks)
- label: t07
  desc: Trust, privacy and deception
- label: t08
  desc: Biometric authentication (camera, voice)
- label: t09
  desc: Identity management

outcomes:
- label: l01
  desc: Explain the concepts of phishing and spear phishing, and how to recognize them. [Familiarity]
- label: l02
  desc: Describe the issues of trust in interface design with an example of a high and low trust system. [Assessment]
- label: l03
  desc: Design a user interface for a security mechanism. [Assessment]
- label: l04
  desc: Explain the concept of identity management and its importance. [Familiarity]
- label: l05
  desc: Analyze a security policy and/or procedures to show where they consider, or fail to consider, human factors. [Usage]
