language: ruby
rvm:
- 2.3.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - SFTP_USER=hepting
exclude:
- vendor
addons:
  ssh_known_hosts: 
    venus.cs.uregina.ca
  apt:
    packages:
    - sshpass

before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
before_install:
- openssl aes-256-cbc -K $encrypted_51a517831301_key -iv $encrypted_51a517831301_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
#- ssh-add deploy_rsa
#- echo 'venus.cs.uregina.ca ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA0MDNrotgbUk4JBkzwhTxNSyVYY81TQVGt/QmTRmjoyB8Lv1/3IKcDR2htfoY+XtlMdkx7gEzG2FmZV7H4phwi32AtmoVJXphU3nFff2gwN/h7X66qWqnsrIsNYUvF2qC5OCX2gv+/osXvtu5wPMwYzEynXA7FI6QnFHuI+o+nC542ZeJXTZS30cpTnXDhB6+dc5K+uma2eruX5v1WC98EM9Q4PCXxMzP0Vi5blWbYNr4NoMSm31cfSytI3bLhSsINUu6cyR5HGNfd/LZhks4lHrbBnYRITjBUfOAzr3AQ9TAF7mkIzEIJIhRfw+6a98tCkMnEsA4hPEhN4q6HNtMCQ==' >> $HOME/.ssh/known_hosts
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
- provider: script
  skip_cleanup: true
  #script: rsync --verbose -e 'sshpass -p $PASSPHRASE ssh' -r --delete-after $TRAVIS_BUILD_DIR/_uregina/ hepting@venus.cs.uregina.ca:_uregina
  script: rsync --verbose -r --delete-after $TRAVIS_BUILD_DIR/_uregina/ hepting@venus.cs.uregina.ca:_uregina
  on:
    branch: master
