language: ruby
rvm:
- 2.3.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - SFTP_USER=hepting
exclude:
- vendor
addons:
  ssh_known_hosts: venus.cs.uregina.ca

before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
before_deploy:
- openssl aes-256-cbc -K $encrypted_51a517831301_key -iv $encrypted_51a517831301_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_uregina/> hepting@venus.cs.uregina.ca:_uregina
  on:
    branch: master
