language: ruby
rvm:
- 2.7.2
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: vpDixJ6De8ewnZ/rO7gQOT15VVTBrw9mdDz2OIeHxs2YP2+REnNJhaDhSKTPRWhS2qFYp7bElyAmon7a28qQaWfGpTOWorHPTdt5/97zWd93HDYe0KKsJuYmdi4SWwoxgUzwgkAh3+SVgRM7thXGkvzOy6xyd7Cqjf/CqVzY11TQaaBr3QjmLPYS79qBxzc4iyRnUXeZeHtbglHrcSjAWlzPCvFVhR6kHM0dgXSHZU44dL09ZCAjkUXVyH3v6hL5j3KLpIwNWza2UhvTXOrinHSsI1b2enJPe12uY+cnt+qNldZqdWVMTdhFC7sgRtnmgO8r9VZFrrXQ4LH4m4JT5u6N1acAaTAu53h5o+3yaQIbcR9YrVxNUo5YDlz1E6vGQ5rpf9tYjACqVrStufGEDXbe/+WXgIU7F5mRmrsW0mNpOoxElfI37+NzdnJFuAu6J5BBI2xsqAjhiD9oasbSEDxYoeoALVgrqpCJ9RY2+zsnxsC/fY+VRaeh+3PsMC6ehZuapYL14F744MDF1cV7DqO8xhgGs6g23CtzOYcHgw79werqraSYSLafZKhIh2plxZCNrDrpkHPDCBPT4c3LITX2ZEdr22cwxL8X59PvZnaqJX8jJ0XCFF6XkZsIbA+YTFgWo6oYA/7zrnOFeNiMlE61zB/Ukv0XAVHhiMZU96Y=
  - secure: CIQwO3bf10IfX0aLgwU5dL2f9jwhYqbZ2CrllP5hlUG8pZLqgrqBo3DdRA3pJq+FF+C4OfCEFOF4Tci1RIgDQFcfysIfPr+oKDd3yul7keDs6yhz6HFmm/E7Q+Itfdg7yYS0Em/r3dUrILm71ukOhoSuaksX0WrJZYOoHznMXEkLKFvhvee7ExBHK0RpOq24H4UdtHY3CYLdMVAQ63GQHV/ACBW/KLj5FE4Sc7rbC++32UoIinnEMszhWnIWSIel+BupGTGlKiw9YTRhhAkDVptfPi43iai+nLYc7XJ8DwjKLpB5rl0J7AiD1lUSTU3/eOVu5wwkpgKPGZA2K+JEgbSh9T4NQ569uaacwTMyY4uMvlq+CuddDbRN0y6gX+6T+S7oaJDx9waeQPQ0y+vO2D7FHeJIqxjp3ilaYIPZKh6OgBb1R7P4rWxAwrUuznUZjuIMzG3qjrU2wB7yv9Nnhe6U9SCUWD/1LN6FXJQPI9wbwoPlhlplo5kh5U5p67pw/OqZ/CxyFbB4iCYbs2DeEmJlxUwsAA6wonGlv6KQrhtvKApyfTRfshSI11RRWTopjolwVAoQ2F0zCmBQmNEVRgt2Q7gIBNhefOaESS0nFBqGSBp2sQKsVWdjdkOng1F3DGb972DTYdCRko13AkmcEv8cJ4aQFPktzCU+U/S3gD4=
  - secure: OilMWqIxNAm75vOQGMtxH0Fr7OjWFvIaIy1ziXgQ+aG4hCXUZ3eqJnpDXjB17GWWgNS3jr9hJ4f8KFJOTy6mrnTMHlbPjWNJE/f7wfvdpJn+iD+C4C5ZqNcVCZB7zBp804c+y5RCunXcYj57viw9283dQFPW3lSB6dFoZw/b0rgyPK4+KwhwDQb51SCdJg3YKEVNdDDrbb+EUnbSWNuHS9enDxoRYowikiwTmRHiW9vsVBkBcU0OO4TeKB833ATDy67pmQR9Mc1jlt9/x3t7FtVURcsKjeWovEn3u0/DEymEUPMS2q9Ozt7QOkO+JZtbD+F5ov9/ZqomwtzNv5fb8xHJXonsilyKkZs5TBnx3S7LuWtJqLtc9FyfjUUtmPqPnBJLF4Zn+KM24BvfewraxOeIw7cs3BGQd5CZfUk35iW3e+7oZqgLtVws2pewTDYJA7P2AGlI0jcDRAWCLdcrTJqTlltcZmRgTiRZZ0NTUqwzGkj1FVroP2mNBJZQGdWbhOkDJMBYPB5aNyO1WInhiw+wCYsJcKjBe53OfWK9AYD6EovA+t79dEmZbopd+Ap1vJf7Jeinzq2vywk3n+xkhLaOYRCmALG1Fvpy3hhav2m29hKl/KqRGiJMNwylwdGmvoCf0IE6j6+tkEoOfXXtzLNTft9JSBz0rH7Yd091jXQ=
exclude:
- vendor
cache: bundler
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
before_install:
- openssl aes-256-cbc -K $encrypted_51a517831301_key -iv $encrypted_51a517831301_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  matrix:
  - provider: pages
    skip_cleanup: true
    token: "$GITHUB_TOKEN"
    keep_history: true
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: rsync --verbose -p -r --delete-after $TRAVIS_BUILD_DIR/_deploy/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIR
    on:
      branch: master
  token:
    secure: Lk7Rl3hXKtS+bQIKCjc7MMcbV1ohRywm8vB6NqCEnO8fbOI9w7zsvi+7gFIhXniLVKc0NjreJxtLcAch1IV+s7t+o+YFt+zMSte6YqvNHl6oLMgnAm3IRKRz2uiaPGSXncPaq2krzRvARFC3G9/oSazceJrPdTzb498979ZQK3nQrNac93ECrlLC9Wyy9/OBcjS71moehN7SW88IOHuXzEBaaVCqZ1/8eJpIPIbhNbzwsMrIlqzeP1BnFMC/uEBbI4E0W/6t9UCF728yy59AAleiBsN56QoRiseAzgj/+15ZwZYC+ex2sSj1JPWqhX3uiDmLIdJHv5gjEaGMiq+6CCsr5luC6gImTUZ8PlmLTYXCUMPCC0Cqla/RQXQUO7lyy5X56tr3V8nCvUPp+qAtIDkdIp7MbGWR6uyL4pBMEug9j20ltV14rpBX/Tc16YtGtW4iJDRZ+jhBc2lAVcU02eL7eJ5lIM+FogcrUKr4QXKMDEB7JQ2D/6EKfEHd6Ywb7Wq9gn8K+TfdLORDBrMpNLVFemrCV/Qudh4/Tru2aUVjX4PPP9YTZbZCi5EOmRsX5B6eBNCuppYxfZ7YkIjG3frAhEsD+OmeH7/ox886efNNfXHKNuPfECM0/tKqxBt8GOFgVB2mPDoFGLnc/z4tWIg7aJroq2iSrzuyAxhn+sI=
