language: ruby
rvm:
- 2.3.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - SFTP_USER=hepting
  - secure: Ksjscb2W+EZ8E09o4QQ34BzG1oEESBPB6L0PGv4YrVthkqHj9xWfNIlvXm5Yjq6ufkn9mVI4WFeNEM4PGZn1BdmASXRm2LyuexYWGWBI0mY5G3ib2C1S9AynJ89TZaXKLQo1zSpcylGxsMmRx3Rp1EukLixUzYiNoczYRp8hm9tnl481te7fCnCvMRUbTXunqp+K6f++bzwvNnoDNSTD5jyYJyyNUdfGBzstCE0MRi9fDLNr58DwbXQvsxNyKfYT81Hdd1MUa0tm8shQHnRCPyjPb9lzd4OvkteqZxL4GGryKLtpk3DWNHp+7BVhri+XRn5T3qr6VBiR5JnBIMfKl/iSAW+rnLGLEr9FAmG+1rhBMR5IhIFy6opQNbdS0MciilYCGiga4wJzI0smUwmKvg3zS6RTFgRsqQPd4iTeJEl0umlm7Bf8fJ3L/IXhja4AnyA3ctLJoEYcWfGYJogBT1sMsSovqfVemfyGANuBFXfWbBMeULj3aYC6OewNknNhA2DP0no5OsiEpaA9DHq7j0vR9rTIgKYFjFpzDbIh+IujQeeV0wQgwVa4D6LjMO+G3/MZdrEobvXDcUalRYTBgQNTBo+5e5mwIHt3M0QQVO9t6OBw0J6q6Ci3V3ZLAlVzWZS61L9109Kq+0ZNz5iVVT7rqTvoR65898j9v7e/FqY=
exclude:
- vendor
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
before_install:
- openssl aes-256-cbc -K $encrypted_51a517831301_key -iv $encrypted_51a517831301_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- echo -e
  "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: rsync --verbose -r --delete-after $TRAVIS_BUILD_DIR/_uregina/ hepting@$DEPLOY_HOST:_uregina
  on:
    branch: master
after_success:
- ssh hepting@$DEPLOY_HOST 'rm -v _uregina/deploy_rsa'
