language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - SFTP_USER=hepting
exclude:
- vendor
addons:
  ssh_known_hosts: venus.cs.uregina.ca
before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc
  -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
sudo: false
after_success:
- bundle exec jekyll build --config "_config.yml,_config_uregina.yml"
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- curl --ftp-create-dirs -T --key /tmp/sftp_rsa sftp://${SFTP_USER}:${SFTP_PASSWORD}@venus.cs.uregina.ca/public_html/
before_install:
- openssl aes-256-cbc -K $encrypted_51a517831301_key -iv $encrypted_51a517831301_iv
  -in deploy_rsa.enc -out deploy_rsa -d
