url: http://www2.cs.uregina.ca
baseurl: /~hepting

webmaster_verifications:
  google: "x1yg5SYk5hD2RE32QX-otdPrCyHgJfRhnidrzYgjONs"
  yandex: "f4086326493c97ca"
  bing: "B58E8EE8B63D2D6869CA610DC73CB57A"

include: ['.htaccess']
