# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
timezone: America/Regina
title: D. H. Hepting, Ph.D.
lang: "en-CA"
email: hepting@cs.uregina.ca
description: >- # this means to ignore newlines until "baseurl:"
  Associate Professor of Computer Science, University of Regina. 
  Ph.D. from Simon Fraser University. Augmenting human abilities to embrace diversity.
baseurl: 
url: https://dhhepting.github.io
github_username:  dhhepting

webmaster_verifications:
# google: "x1yg5SYk5hD2RE32QX-otdPrCyHgJfRhnidrzYgjONs"
  google: "gsgGWE8pmuMxDXPcvsS7ukLSHeWoZWuMBqXIzCMiF04"
  bing:   "F1CCB2E1C91FDC5B8A82937F80B46C0A"
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


sass:

# Exclude from processing.
exclude:
  - README.md
  - node_modules
  - package.json
  - script
  - vendor
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - teaching/0_nonweb
  - research/0_nonweb
  - teaching/1_offweb

# Keep from being clobbered on each build
keep_files:
  - assets/works

# permalink for _posts (news)

collections:
  - works

collections:
  posts:
    output: true
    permalink: /:categories/:name:output_ext
  works:
    output: true
    permalink: /research/:collection/:name:output_ext

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "default"
      author: "Daryl H. Hepting"
