# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
timezone: America/Regina
title: D. H. Hepting, Ph.D.
lang: "en-CA"
encoding: utf-8
email: hepting@cs.uregina.ca
description: >- # this means to ignore newlines until "baseurl:"
  Associate Professor of Computer Science, University of Regina.
  Ph.D. from Simon Fraser University. Augmenting human abilities to embrace diversity.
baseurl:
url: https://dhhepting.github.io
canonical: http://www2.cs.uregina.ca/~hepting
github_username:  dhhepting

webmaster_verifications:
# google: "x1yg5SYk5hD2RE32QX-otdPrCyHgJfRhnidrzYgjONs"
  google: "gsgGWE8pmuMxDXPcvsS7ukLSHeWoZWuMBqXIzCMiF04"
  bing:   "F1CCB2E1C91FDC5B8A82937F80B46C0A"
#  yandex: "f4086326493c97ca"
  yandex: "624aa53b50cad90a"



# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# feed:
#   path: rss/news.xml

sass:

# Exclude from processing.
exclude:
  - deploy_rsa
  - deploy_rsa.enc
  - README.md
  - node_modules
  - package.json
  - script
  - vendor
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - teaching/0_nonweb/
  - teaching/CS-205/0_nonweb/
  - teaching/CS-205/201910/0_nonweb/
  - teaching/CS-205/201910/1_offweb/
  - teaching/CS-280/0_nonweb/
  - teaching/CS-280/201910/0_nonweb/
  - teaching/CS-280/201910/1_offweb/
  - teaching/CS-428+828/0_nonweb/
  - teaching/CS-428+828/201630/0_nonweb/
  - teaching/CS-428+828/201630/1_offweb/
  - teaching/CS-428+828/201730/0_nonweb/
  - teaching/CS-428+828/201730/1_offweb/
  - teaching/CS-428+828/201830/0_nonweb/
  - teaching/CS-428+828/201830/1_offweb/
  - teaching/CS-428+828/201930/0_nonweb/
  - teaching/CS-428+828/201930/1_offweb/
  - teaching/CS-499+900/201920/0_nonweb/
  - teaching/CS-499+900/201920/1_offweb/
  - teaching/schedule/0_nonweb/
  - research/0_nonweb/
  - research/works/0_nonweb/
  - research/students/0_nonweb/
  - research/funding/0_nonweb/

# Keep from being clobbered on each build
keep_files:
  - assets/works

tipue_search:
  include:
    pages: true
    collections: [works, gallery]
  exclude:
    files: [search.html]
    tags:
    categories:

# permalink for _posts (news)

collections:
  - works
  - gallery
  - assignments

collections:
  posts:
    output: true
    permalink: /:categories/:title:output_ext
  works:
    output: true
    permalink: /research/:collection/:title:output_ext
  gallery:
    output: true
    permalink: /projects/fractals/:collection/:title:output_ext
  assignments:
    output: false
    permalink: /teaching/:collection/:path/:categories/:title:output_ext

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Daryl H. Hepting"
