#!/usr/bin/env python3
"""
gen-offweb-migration.py

Scan the repo for legacy off-web directories -- 0_nonweb, 0-nonweb, 1_offweb --
and WRITE a shell script (migrate-offweb.sh) that, for each one:

  * mkdir -p's the mirrored destination parent under _offweb/ or _nonweb/, and
  * git mv's the legacy directory into that mirrored location.

The mapping mirrors the full path (the legacy marker segment is dropped and the
remaining path is re-rooted under the archive dir), e.g.:

    teaching/CS-110/1_offweb             ->  _offweb/teaching/CS-110
    teaching/CS-428+828/202130/0-nonweb  ->  _nonweb/teaching/CS-428+828/202130

IMPORTANT: this generator MOVES NOTHING. It only writes a script for you to
review and then run yourself. Run it from the root of your repo.

Discovery uses `git ls-files`, so it only finds directories that are actually
tracked -- which is exactly what `git mv` can move, and keeps the migration in
sync with what CI will build.
"""

import os
import stat
import subprocess
import sys
from pathlib import PurePosixPath

OFFWEB_SEGMENTS = {"1_offweb"}
NONWEB_SEGMENTS = {"0_nonweb", "0-nonweb"}
LEGACY_SEGMENTS = OFFWEB_SEGMENTS | NONWEB_SEGMENTS
OUTPUT = "migrate-offweb.sh"


def tracked_files():
    """All git-tracked paths, or exit if we're not in a repo.

    Uses `-z` (NUL-separated output) deliberately. By default `git ls-files`
    applies core.quotePath: any path with "unusual" bytes (non-ASCII, quotes,
    etc.) comes back wrapped in double quotes and C-escaped -- e.g. an accented
    filename returns as "teaching/.../caf\\303\\251.js" WITH the surrounding
    quotes. Splitting that on "/" leaks a stray " into the first path segment,
    which both corrupts the move AND defeats the _offweb/_nonweb skip guard
    (because '"_nonweb' != '_nonweb'). `-z` emits raw, unquoted pathnames, so
    filenames containing any character are read correctly.
    """
    result = subprocess.run(["git", "ls-files", "-z"], capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit("error: could not run `git ls-files` -- run this from inside the repo.")
    return [path for path in result.stdout.split("\0") if path]


def find_legacy_roots(files):
    """Map each unique legacy directory to its archive root (_offweb / _nonweb).

    For each tracked file, find the FIRST path segment that is a legacy marker;
    everything up to and including it is the directory to move. Using the first
    (outermost) marker means a nested marker is carried along by its parent
    rather than moved separately.
    """
    roots = {}
    for path in files:
        parts = path.split("/")
        # Skip anything already inside an archive tree -- it has been migrated
        # already. Without this, a re-run (or a legacy marker nested inside
        # content moved on a previous run) would get moved a SECOND time into a
        # nonsensical _nonweb/_offweb/... path. This is the re-run safety fix.
        if any(seg in ("_offweb", "_nonweb") for seg in parts):
            continue
        idx = next((i for i, seg in enumerate(parts) if seg in LEGACY_SEGMENTS), None)
        if idx is None:
            continue
        src_root = "/".join(parts[: idx + 1])
        marker = parts[idx]
        roots[src_root] = "_offweb" if marker in OFFWEB_SEGMENTS else "_nonweb"
    return dict(sorted(roots.items()))


def plan_moves(roots):
    """Yield (src, dest, dest_parent) for each legacy directory."""
    for src, archive in roots.items():
        p = PurePosixPath(src)
        parent = str(p.parent)  # path above the marker segment
        if parent == ".":
            # marker sat at the repo root (unusual) -- mirror by its own name
            dest = f"{archive}/{p.name}"
        else:
            dest = f"{archive}/{parent}"
        dest_parent = str(PurePosixPath(dest).parent)
        yield src, dest, dest_parent


def write_script(moves):
    """Write the migration script; return the number of moves."""
    lines = [
        "#!/usr/bin/env bash",
        "# migrate-offweb.sh -- GENERATED by gen-offweb-migration.py. REVIEW before running.",
        "# Moves legacy off-web dirs into mirrored _offweb/ and _nonweb/ trees.",
        "# Each block is idempotent: it skips when the source is gone or the dest already",
        "# exists, so re-running after a partial run is safe.",
        "set -euo pipefail",
        "",
        "if [ ! -d .git ] || [ ! -d teaching ]; then",
        '  echo "Run this from the root of your repo (where .git and teaching/ live)." >&2',
        "  exit 1",
        "fi",
        "",
    ]
    count = 0
    for src, dest, dest_parent in moves:
        lines += [
            f"# {src}  ->  {dest}",
            f'if [ -e "{src}" ] && [ ! -e "{dest}" ]; then',
            f'  mkdir -p "{dest_parent}"',
            f'  git mv "{src}" "{dest}"',
            f'  echo "moved: {src} -> {dest}"',
            "else",
            f'  echo "skip:  {src} (source missing or destination already exists)"',
            "fi",
            "",
        ]
        count += 1

    with open(OUTPUT, "w") as f:
        f.write("\n".join(lines) + "\n")

    st = os.stat(OUTPUT)
    os.chmod(OUTPUT, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return count


def main():
    roots = find_legacy_roots(tracked_files())
    if not roots:
        print("No 0_nonweb / 0-nonweb / 1_offweb directories found in tracked files.")
        print("Nothing to migrate.")
        return

    moves = list(plan_moves(roots))

    # Preview the plan to stdout so you see it before opening the file.
    print(f"Found {len(moves)} legacy off-web director{'y' if len(moves) == 1 else 'ies'}:\n")
    width = max(len(src) for src, _, _ in moves)
    for src, dest, _ in moves:
        print(f"  {src:<{width}}  ->  {dest}")

    count = write_script(moves)
    print(f"\nWrote {OUTPUT} with {count} move(s).")
    print(f"  Review:  less {OUTPUT}")
    print(f"  Run:     ./{OUTPUT}")
    print("\nBefore running the migration script:")
    print("  1. Do the node_modules cleanup first (gitignore + git rm --cached).")
    print("  2. Remove any `code -> 1_offweb/code` symlinks -- moving 1_offweb will")
    print("     otherwise leave them dangling.")


if __name__ == "__main__":
    main()
