language: ruby
rvm:
- 2.3.3

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# branch whitelist, only for GitHub Pages
#branches:
#  only:
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - 'SFTP_USER=hepting'
  - 'SFTP_KEY=AAAAB3NzaC1yc2EAAAABIwAAAQEAz7TZ4vXhv5jyXeAX/IADb4elhY8kftbX6ESyTQdoFyBsuhF8is3FKi+tWH6b/vWOdMoZkdklIqrItUYG5OUkoJAn6GjQJQoiFDcwT0sYeRnaQbE1c/XHeBbznT90bIvefCwIwT1YU1pYzNGT2kTnyaeHdXQ4h8jReJ6ygwT1jy1PSiQoindITwgn0Xrqfnekj+9pnREf4Le9uYU0oNweKOap3tRn6mpeO8M1zxfMC1cNpEyn2k1aKsNyAzX8EtdKUZvqIekwBOIF8crKL/FXRxd9RxM/TD2hSJFpzJcA9cLwZiBFK+/q0vY18XRckSIlq2awHzFzM8+eYxgg1AE5lQ=='

exclude: [vendor]

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

sudo: false # route your build to the container-based infrastructure for a faster build

after_success:
- echo "UREGINA"
- bundle exec jekyll build --config "_config.yml,_config_uregina.yml"
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- curl --ftp-create-dirs
       -T --key /tmp/sftp_rsa sftp://${SFTP_USER}:${SFTP_PASSWORD}@venus.cs.uregina.ca/public_html/filename
